/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mananger;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import mananger.item.*;
import mananger.shelf.*;

/**
 *
 * @author coc
 */
public class ItemManager extends javax.swing.JFrame {

    DefaultListModel dm = new DefaultListModel();
    
    /**
     * Creates new form ItemManager
     */
    public ItemManager() {
        initComponents();
        try{
            reloadList();
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_items = new javax.swing.JList<>();
        btn_load = new javax.swing.JButton();
        lb_itemid = new javax.swing.JLabel();
        btn_remove = new javax.swing.JButton();
        txt_itemid = new javax.swing.JTextField();
        lb_itemname = new javax.swing.JLabel();
        txt_itemname = new javax.swing.JTextField();
        lb_itemprice = new javax.swing.JLabel();
        txt_itemprice = new javax.swing.JTextField();
        combo_itemtype = new javax.swing.JComboBox<>();
        lb_itemprice1 = new javax.swing.JLabel();
        lb_special = new javax.swing.JLabel();
        txt_special = new javax.swing.JTextField();
        btn_additem = new javax.swing.JButton();

        setTitle("Item Manager");

        list_items.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_items.setToolTipText("");
        jScrollPane1.setViewportView(list_items);

        btn_load.setText("Reload");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        lb_itemid.setText("Item ID:");

        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        lb_itemname.setText("Item Name:");

        lb_itemprice.setText("Item Price:");

        combo_itemtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Item", "Food", "Book", " " }));
        combo_itemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_itemtypeActionPerformed(evt);
            }
        });

        lb_itemprice1.setText("Item Type:");

        lb_special.setText("Food Weight:");
        lb_special.setEnabled(false);

        txt_special.setEnabled(false);

        btn_additem.setLabel("Add Item");
        btn_additem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_additemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(btn_load, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_itemid)
                    .addComponent(txt_itemid)
                    .addComponent(lb_itemname)
                    .addComponent(txt_itemname)
                    .addComponent(lb_itemprice)
                    .addComponent(txt_itemprice)
                    .addComponent(lb_itemprice1)
                    .addComponent(combo_itemtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_special)
                    .addComponent(txt_special)
                    .addComponent(btn_additem, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lb_itemid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_itemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_itemname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_itemprice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lb_itemprice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_itemtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_special)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_special, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btn_additem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_itemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_itemtypeActionPerformed
        String selecteditem = String.valueOf(combo_itemtype.getSelectedItem());
        if(selecteditem.equalsIgnoreCase("Normal Item")){
            lb_special.setEnabled(false);
            txt_special.setEnabled(false);
        }else if(selecteditem.equalsIgnoreCase("Food")){
            lb_special.setEnabled(true);
            txt_special.setEnabled(true);
            lb_special.setText("Weight: ");
        }else{
            lb_special.setEnabled(true);
            txt_special.setEnabled(true);
            lb_special.setText("Author: ");
        }
        
    }//GEN-LAST:event_combo_itemtypeActionPerformed

    private void btn_additemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_additemActionPerformed
        String selecteditem = String.valueOf(combo_itemtype.getSelectedItem());
        if(txt_itemid.getText().trim().equals("") || txt_itemname.getText().trim().equals("") || 
        txt_itemprice.getText().trim().equals("") ||
         (txt_special.getText().trim().equals("") && (selecteditem.equalsIgnoreCase("Food") || selecteditem.equalsIgnoreCase("Book"))))
            return;
        
        try{
            int id = Integer.parseInt(txt_itemid.getText());
            String name = txt_itemname.getText();
            double price = Double.parseDouble(txt_itemprice.getText());
            String special = txt_special.getText();
            if(selecteditem.equalsIgnoreCase("Food")){
                Registry.itemarray.add(new Foods(id, name, price, Double.parseDouble(special)));
            }else if(selecteditem.equalsIgnoreCase("Book")){
                Registry.itemarray.add(new Books(id, name, price, special));
            }else{
                Registry.itemarray.add(new Items(id, name, price));
            }
            saveAllToFile();
            reloadList();
        }catch(Exception e){}
    }//GEN-LAST:event_btn_additemActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        int selectindex = list_items.getSelectedIndex();

        Registry.removeItem(selectindex);
        try{
            saveAllToFile();
            reloadList();
            
        }catch(Exception e){}
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        try{
            reloadList();
        }catch(Exception e){}
    }//GEN-LAST:event_btn_loadActionPerformed

    /**
     * @param args the command line arguments
     */

    public void reloadList()throws FileNotFoundException, IOException{
        dm.clear();
        File file=new File("items.txt");    //creates a new file instance  
        FileReader fr=new FileReader(file);   //reads the file  
        BufferedReader br=new BufferedReader(fr);  //creates a buffering character input stream  
        StringBuffer sb=new StringBuffer();    //constructs a string buffer with no characters  
        String line;  
        while((line=br.readLine())!=null)  
        {  
            dm.addElement(line.replaceAll(",", " "));
        }  
        fr.close();    //closes the stream and release the resources  
        list_items.setModel(dm);
    }
    
    public void saveAllToFile()throws IOException {
        FileWriter w = new FileWriter("items.txt");
        for(Items i : Registry.itemarray){
            w.write(i.getString() + "\n");
        }
        w.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_additem;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> combo_itemtype;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_itemid;
    private javax.swing.JLabel lb_itemname;
    private javax.swing.JLabel lb_itemprice;
    private javax.swing.JLabel lb_itemprice1;
    private javax.swing.JLabel lb_special;
    private javax.swing.JList<String> list_items;
    private javax.swing.JTextField txt_itemid;
    private javax.swing.JTextField txt_itemname;
    private javax.swing.JTextField txt_itemprice;
    private javax.swing.JTextField txt_special;
    // End of variables declaration//GEN-END:variables
}
