/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mananger;

import java.io.FileWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import mananger.item.*;
import mananger.shelf.Shelf;
/**
 *
 * @author coc
 */
public class ShelfManager extends javax.swing.JFrame {

    
    DefaultListModel shelf_dm = new DefaultListModel();
    DefaultListModel itemshelf_dm = new DefaultListModel();
    DefaultListModel items_dm = new DefaultListModel();
    /**
     * Creates new form ShelfManager
     */
    public ShelfManager() {
        initComponents();
        reloadItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_shelf = new javax.swing.JList<>();
        btn_addshelf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_shelfid = new javax.swing.JTextField();
        btn_removeshelf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_iteminshelf = new javax.swing.JList<>();
        btn_removeiteminshelf = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_currentitem = new javax.swing.JList<>();
        btn_addtoshelf = new javax.swing.JButton();
        btn_reload = new javax.swing.JButton();

        setTitle("Shelf Manager");

        jLabel1.setText("Current Shelf");

        list_shelf.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_shelfValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_shelf);

        btn_addshelf.setText("Add");
        btn_addshelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addshelfActionPerformed(evt);
            }
        });

        jLabel2.setText("Shelf Id:");

        btn_removeshelf.setText("Remove");

        jLabel3.setText("Item In Shelf");

        jScrollPane2.setViewportView(list_iteminshelf);

        btn_removeiteminshelf.setText("Remove");
        btn_removeiteminshelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeiteminshelfActionPerformed(evt);
            }
        });

        jLabel4.setText("All Items");

        jScrollPane3.setViewportView(list_currentitem);

        btn_addtoshelf.setText("Add To Current Shelf");
        btn_addtoshelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addtoshelfActionPerformed(evt);
            }
        });

        btn_reload.setText("Reload");
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(311, 311, 311)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_removeshelf, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txt_shelfid)
                            .addComponent(btn_addshelf, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_removeiteminshelf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(btn_addtoshelf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_removeshelf)
                            .addComponent(btn_removeiteminshelf)
                            .addComponent(btn_addtoshelf)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_shelfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_addshelf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed
        reloadItem();
        reloadShelf();
        reloadInShelf();
    }//GEN-LAST:event_btn_reloadActionPerformed

    private void btn_addshelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addshelfActionPerformed
        if(txt_shelfid.getText().trim().equalsIgnoreCase(""))return;
        try{
            int id = Integer.parseInt(txt_shelfid.getText());
            Registry.shelfarray.add(new Shelf(id));
            reloadShelf();
            saveShelfToFile();
        }catch(Exception e){}
    }//GEN-LAST:event_btn_addshelfActionPerformed

    private void list_shelfValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_shelfValueChanged
        reloadInShelf();
    }//GEN-LAST:event_list_shelfValueChanged

    private void btn_addtoshelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addtoshelfActionPerformed
        int index = list_shelf.getSelectedIndex();
        int i_dex = list_currentitem.getSelectedIndex();
        if(index == -1 || i_dex == -1)return;
        Registry.shelfarray.get(index).item_Have.add(Registry.itemarray.get(i_dex));
        Registry.shelfarray.get(index).item_Have_index.add(i_dex);
        reloadInShelf();
        saveShelfToFile();
    }//GEN-LAST:event_btn_addtoshelfActionPerformed

    private void btn_removeiteminshelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeiteminshelfActionPerformed
        int i_dex = list_iteminshelf.getSelectedIndex();
        int index = list_shelf.getSelectedIndex();
        if(index == -1 || i_dex == -1)return;
        Registry.shelfarray.get(index).item_Have.remove(i_dex);
        Registry.shelfarray.get(index).item_Have_index.remove(i_dex);
        reloadInShelf();
        saveShelfToFile();
    }//GEN-LAST:event_btn_removeiteminshelfActionPerformed

    public void reloadInShelf(){
        int index = list_shelf.getSelectedIndex();
        if(index == -1)return;
        itemshelf_dm.clear();
        for(Items i : Registry.shelfarray.get(index).item_Have){
            itemshelf_dm.addElement(i.getString().replaceAll(",", " "));
        }
        list_iteminshelf.setModel(itemshelf_dm);
    }
    
    public void reloadItem(){
        items_dm.clear();
        for(Items i : Registry.itemarray){
            items_dm.addElement(i.getString().replaceAll(",", " "));
        }
        list_currentitem.setModel(items_dm);
    }
    
    public void reloadShelf(){
        shelf_dm.clear();
        for(Shelf i : Registry.shelfarray){
            shelf_dm.addElement("Shelf: " + i.getId());
        }
        list_shelf.setModel(shelf_dm);
    }

    public void saveShelfToFile(){
        try{
            FileWriter w = new FileWriter("shelf.txt");
            for(Shelf i : Registry.shelfarray){
                w.write("Id:" + i.getId() + "/-1");
                for(Items e : i.item_Have){
                    w.write("," + e.getID());
                }
                w.write("\n");
            }
            w.close();
        }catch(Exception e){}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addshelf;
    private javax.swing.JButton btn_addtoshelf;
    private javax.swing.JButton btn_reload;
    private javax.swing.JButton btn_removeiteminshelf;
    private javax.swing.JButton btn_removeshelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list_currentitem;
    private javax.swing.JList<String> list_iteminshelf;
    private javax.swing.JList<String> list_shelf;
    private javax.swing.JTextField txt_shelfid;
    // End of variables declaration//GEN-END:variables
}
